name: Bunnyshell - Deploy Preview Environment
concurrency: bns-deploy-${{ github.event.number || github.event.issue.number }}
on:
  workflow_dispatch:
    inputs:
      argocd_image:
        description: 'ArgoCD image to use'     
        required: true
        default: 'quay.io/argoproj/argocd:latest'
jobs:
  deploy:
    name: Deploy Environment
    uses: bunnyshell/workflows/.github/workflows/deploy-env.yaml@main
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      env-name: 'ArgoCD PR #${{ github.event.number || github.event.issue.number }}'
      bunnyshell-yaml-path: .bunnyshell/templates/preview/bunnyshell.yaml
      allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
      comment-on-pr: true
      deploy-as-stopped: true
      git-ref: refs/pull/${{ github.event.number || github.event.issue.number }}/head
      restricted-files: |
          .bunnyshell/*
      use-app-token: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
      app-private-key: ${{ secrets.BUNNYSHELL_APP_PRIVATE_KEY }}
