name: Bunnyshell - Deploy Preview Environment
concurrency: bns-deploy-${{ github.event.number || github.event.issue.number }}
on:
  workflow_run:
    workflows:
      - "Image"
    types:
      - completed
  issue_comment:
    types: [ created, edited ]
jobs:
  load-artifact:
    name: Load bunnyshell artifact
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      pr-number: ${{ env.PR_NUMBER }}
      is-pull-request-event: ${{ env.IS_PULL_REQUEST }} #todo bns: do I need this?
      image-name: ${{ env.IMAGE_NAME }}
    steps:
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: | #todo bns: can I replace these with: gh run download <run-id> -n <name> --dir The directory to download artifacts into (default ".")
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "bunnyshell"
            })[0];
            if (matchArtifact === undefined) {
              throw TypeError('Bunnyshell Artifact not found!');
            }
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/artifact.zip`, Buffer.from(download.data));
      - name: Load artifact data
        run: |
          unzip artifact.zip

          echo 'EVENT_JSON<<EOFEVENTJSON' >> $GITHUB_ENV
          cat event.json >> $GITHUB_ENV
          echo -e '\nEOFEVENTJSON' >> $GITHUB_ENV

          echo 'DATA_JSON<<EOFDATAJSON' >> $GITHUB_ENV
          cat data.json >> $GITHUB_ENV
          echo -e '\nEOFDATAJSON' >> $GITHUB_ENV

      - name: Set variables
        run: |
          echo "IS_PULL_REQUEST=${{ fromJSON(env.EVENT_JSON).pull_request != '' }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ fromJSON(env.EVENT_JSON).issue.number || fromJSON(env.EVENT_JSON).number }}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ fromJSON(env.DATA_JSON).image_name }}" >> $GITHUB_ENV

      - name: Configure Bunnyshell AWS Credentials
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
        with:
          aws-access-key-id: ${{ secrets.bunnyshell_cr_username }}
          aws-secret-access-key: ${{ secrets.bunnyshell_cr_password }}
          aws-region: eu-west-1

      - name: Login to Bunnyshell Container Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: 904643107945.dkr.ecr.eu-west-1.amazonaws.com

      - name: Push image to Bunnyshell Container Registry
        run: |
          docker load --input image.tar
          docker push ${{ env.IMAGE_NAME }}

  prepare:
    permissions:
      contents: read
    needs: load-artifact
    if: ${{ always() }}
    runs-on: ubuntu-22.04
    outputs:
      bunnyshell-yaml-contents: ${{ steps.prepare-bunnyshell-yaml.outputs.contents }}
      git-ref: ${{ steps.determine-git-ref.outputs.git-ref }}
    steps:
      - name: setup-yq
        uses: frenck/action-setup-yq@c4b5be8b4a215c536a41d436757d9feb92836d4f # v1.0.2
      - name: determine-git-ref
        id: determine-git-ref
        run: |
          gitRef="${{ format('refs/pull/{0}/head', needs.load-artifact.outputs.pr-number || github.event.issue.number) }}"

          echo "git-ref=$gitRef" >> "$GITHUB_OUTPUT"
      - name: Compute artifacts names
        run: |
          artifactName="argocd-image-${{ needs.load-artifact.outputs.pr-number || github.event.issue.number }}.txt"
          echo "artifactName=$artifactName" >> "$GITHUB_ENV"
      - name: Write artifacts
        if: ${{ needs.load-artifact.outputs.image-name }}
        run: |
          echo "${{ needs.load-artifact.outputs.image-name }}" > ${{ env.artifactName }}
      - name: Upload artifacts
        if: ${{ needs.load-artifact.outputs.image-name }}
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce #v3.1.2
        with:
          name: ${{ env.artifactName }}
          path: ${{ env.artifactName }}
      - name: Check out the repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.3.0
        with:
          ref: ${{ steps.determine-git-ref.outputs.git-ref }}
          fetch-depth: 0
      - name: Prepare vars
        id: prepare-vars
        run: |
          echo "BNS_GIT_SHA=`git rev-parse --short HEAD`" >> "$GITHUB_ENV"

          echo "BNS_BUNNYSHELL_YAML_PATH=${{ '.bunnyshell/templates/preview/bunnyshell.yaml' }}" >> "$GITHUB_ENV"

          artifactArgocdImage=""
          if [ "${{ needs.load-artifact.outputs.image-name }}" == "" ]; then

            # this will also exit if no artifact was created before
            gh run download -n ${{ env.artifactName }}

            artifactArgocdImage=$(cat ${{ env.artifactName }})

            # exit if artifact is empty, cannot continue
            if [ "$artifactArgocdImage" == "" ]; then
              echo "No argocd-image to use."
              exit 1
            fi

            echo "BNS_ARGOCD_IMAGE=$artifactArgocdImage" >> "$GITHUB_ENV"
          else
            echo "BNS_ARGOCD_IMAGE=${{ needs.load-artifact.outputs.image-name }}" >> "$GITHUB_ENV"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Prepare bunnyshell.yaml
        id: prepare-bunnyshell-yaml
        run: |
          set -e
  
          # update branch
          yq "(.components[] | select(.gitBranch != null)).gitBranch |= \"${{ env.BNS_GIT_SHA }}\"" ${{ env.BNS_BUNNYSHELL_YAML_PATH }} > bunnyshell_wf_updated.yaml

          # set environmentVariables
          yq -i ".environmentVariables.ARGOCD_IMAGE |= \"${{ env.BNS_ARGOCD_IMAGE }}\"" bunnyshell_wf_updated.yaml

          # set application variables
          yq -i "(.components[] | select(.name == \"argocd-ttyd\")).environment.ARGOCD_PASS |= \"bns_secret(${{ secrets.bunnyshell_preview_password }})\"" bunnyshell_wf_updated.yaml

          # encode the bunnyshell.yaml, as it contains secrets, to be able to pass it between jobs
          result=$(gpg --symmetric --cipher-algo AES256 --batch --passphrase "${{ secrets.bunnyshell_encryption_passphrase }}" --output - bunnyshell_wf_updated.yaml | base64 -w0)
       
          # set outputs
          echo "contents=$result" >> "$GITHUB_OUTPUT"

  deploy:
    permissions:
      pull-requests: write
    name: Deploy Environment
    needs: prepare
    if: ${{ github.event_name == 'issue_comment' || (github.event_name == 'pull_request' }} #todo bns: fix also with labels && contains(github.event.pull_request.labels.*.name, 'bns:preview')) }}
    uses: bunnyshell/workflows/.github/workflows/prepare-and-deploy-env.yaml@f7f9ad94030d3e5c69c72f2d480bd360acb5545c # v1.0.3 #todo bns: fix to a gitSha
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      cluster-id: ${{ vars.BUNNYSHELL_CLUSTER_ID }}
      env-name: 'ArgoCD PR #${{ github.event.number || github.event.issue.number }}'
      bunnyshell-yaml-contents: ${{ needs.prepare.outputs.bunnyshell-yaml-contents }}
      allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
      comment-on-pr: true
      deploy-as-stopped: ${{ github.event_name == 'pull_request' }}
      git-ref: ${{ needs.prepare.outputs.git-ref }}
      restricted-files: |
          .bunnyshell/*
    secrets:
      bunnyshell-access-token: ${{ secrets.bunnyshell_access_token }}
      bunnyshell-yaml-contents-encryption-passphrase: ${{ secrets.bunnyshell_encryption_passphrase }}
