name: Bunnyshell - Stop Preview Environment

concurrency: bns-start-stop-${{ github.event.issue.number }}

on:
  issue_comment:
    types: [created, edited]

jobs:
  start:
    permissions:
      pull-requests: write
    name: Stop Environment
    uses: bunnyshell/workflows/.github/workflows/stop-env.yaml@02c93566e977ac0918432f253e70a4a3b4893884 # v1.0.4 #todo bns: fix to a gitSha
    with:
      project-id: ${{ vars.BUNNYSHELL_PROJECT_ID }}
      env-name: 'ArgoCD PR #${{ github.event.issue.number }}'
      allowed-users: ${{ vars.BUNNYSHELL_ALLOWED_USERS }}
      comment-on-pr: true
    secrets:
      bunnyshell-access-token: ${{ secrets.BUNNYSHELL_ACCESS_TOKEN }}
